[build]
    command = "GATSBY_CONCURRENT_DOWNLOAD=25 yarn workspace gatsby-theme-farming-revolution build"
  	functions = "gatsby-theme-farming-revolution/src/api"
    publish = "gatsby-theme-farming-revolution/public"

[build.environment]
  NODE_VERSION = "18.12.1"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-local-install-core"
