[build]
    command = "GATSBY_CONCURRENT_DOWNLOAD=25 npm run build --workspace=gatsby-theme-v5-boilerplate"
  	functions = "gatsby-theme-v5-boilerplate/src/api"
    publish = "gatsby-theme-v5-boilerplate/public"

[build.environment]
  NODE_VERSION = "18.12.1"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-local-install-core"
